### ISSUE TITLE
Chat Message when Player uses Token Lean

### ISSUE THREAD

**Issue by apoapostolov** [WesBelmont/token-lean#22]
In PF2, Leaning from Cover is an actual action that costs 1A during encounters. See this video https://www.youtube.com/watch?v=h2kdsJ8XzIY for information.

The problem is, Token Lean can be used freely by players and some players might cheat to Lean without saying they do, and it reveals information that they should be able to reveal if they pay 1A to Lean. But if they can do it anytime, without telling the DM, they can cheat and use it without saying how they know there's enemy around a corner, for example.

This can be very easily fixed if the GM gets a very small chat message every time a player uses the Lean functionality.

**Comment by WesBelmont** [comment]
I did have a version that had settings for disallowing leaning in combat/when paused. I can add an option to whisper a notification when a token leans/when a token leans in combat. I will also add an option to only post the notification once per turn, so that the module does not spam the chat log.

A toggle in the game controls is probably a good tool as well. Then in combat leaning can be disallowed quickly and accessibly.

**Comment by WesBelmont** [comment]
Included in version 1.4.0
